name: daily_task_reminder
description: A daily task reminder app with notifications
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Local Database
  sqflite: ^2.3.0
  path: ^1.8.3

  # Notifications & Background Tasks
  flutter_local_notifications: 18.0.1
  workmanager: ^0.9.0+3 # Updated to latest version

  # Utilities
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
